title: Portfolio CMS
baseurl: "/cms"
url: "https://MohammadAmmar.883742.xyz"

# Jekyll settings
markdown: kramdown
permalink: /:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
